---
- name: Ensuring EPEL repo
  dnf:
    name: epel-release.noarch
    state: present

- name: Installing Nginx
  dnf:
    name: nginx

- name: Enable and start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Enusre firewalld is running
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Enabling ports for Nginx Serivces 
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ centos_nginx_ports }}"
