---
- name: Creating Self Signed SSL certificate config
  template:
    src: templates/greeneagledev/self-signed.conf.j2
    dest: /etc/nginx/snippets/self-signed.conf


- name: Creating SSL PARAMS strong encryption config
  template:
    src: templates/greeneagledev/ssl-params.conf.j2
    dest: /etc/nginx/snippets/ssl-params.conf
