---
# tasks file for nginx
- name: Deploying Nginx on kibana
  include: CentOS-kibana.yml
  when: "'kibana' in group_names"

- name: Deploying Nginx on CentOS boxes
  include: CentOS.yml
  when:
    ansible_distribution == "CentOS"

- name: Deploying Nginx on greeneagledev
  include: Ubuntu-greeneagledev.yml
  when: "'greeneagledev' in group_names"

- name: Deploying Nginx on greeneagledev
  include: Ubuntu-shoplauncherdev.yml
  when: "'shoplauncherdev' in group_names"

- name: Deploying Nginx on Ubuntu boxes
  include: Ubuntu-stockcheck.yml
  when: "'stockcheck' in group_names"

- name: Deploying Nginx on Ubuntu boxes
  include: Ubuntu.yml
  when:
    ansible_distribution == "Ubuntu"
