---
# tasks file for Apache
- name: Deploying apache for stockcheck
  include: stockcheck.yml
  when: "'stockcheck' in group_names"

- name: Deploying Apache on CentOS boxes
  include: CentOS.yml
  when:
    ansible_distribution == "CentOS"

- name: Deploying Apache on Ubuntu boxes
  include: Ubuntu.yml
  when:
    ansible_distribution == "Ubuntu"
