- name: Create greeneagledev01 instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  tasks:
    - name: create a disk mapped for greeneagledev01 - Ubuntu 20.04
      gcp_compute_disk:
        name: greeneagledev01-disk-instance
        size_gb: 200
        type: pd-ssd
        source_image: "{{ ubuntuimage }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk

    - name: create a greeneagledev VPC network
      gcp_compute_network:
        name: shoplauncherdev-subnetwork
        auto_create_subnetworks: 'true'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: network

    - name: create a firewall rules for VPC
      gcp_compute_firewall:
        name: greeneagledev-fw-ports
        network: "{{ network }}"
        allowed:
          - ip_protocol: icmp
          - ip_protocol: tcp
            ports:
              - '22'
              - '80'
              - '443'
        target_tags:
          - greeneagledev
        source_tags:
          - greeneagledev
          - shoplauncherdev
          - management
          - greeneagle
          - redis
          - elasticsearch
        source_ranges:
          - '0.0.0.0/0'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: firewall

    - name: create an IPv4 public IP Address
      gcp_compute_address:
        name: greeneagledev01-instance
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: address

    - name: create the greeneagledev01 instance
      gcp_compute_instance:
        name: greeneagledev01
        machine_type: "{{ machine_type.shoplauncherdev }}"
        deletion_protection: yes
        disks:
          - index: 0
            auto_delete: 'no'
            boot: 'true'
            source: "{{ disk }}"
        labels:
          environment: greeneagledev
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - greeneagledev
        metadata:
          ssh_user: "{{ ssh_user }}"
          ssh_key: "{{ ssh_key }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: instance

    - name: Show greeneagledev01 Instance Details
      debug:
        msg: "The greeneagledev01 instance is accessible at {{ address.address }}"

    - name: Add greeneagledev01 to group greeneagledev01
      add_host:
        name: "{{ address.address }}"
        groups: greeneagledev

  post_tasks:
    - name: Wait for SSH for instance greeneagledev01 in first zone
      wait_for:
        delay: 30
        host: "{{ address.address }}"
        port: 22
        state: started
        timeout: 120

- hosts: greeneagledev
  roles:
    - php74
    - nginx
    - users
      #- mariadb
  gather_facts: True
  become: true
  vars:
    ansible_user: chudieagle
    ansible_ssh_private_key_file: /home/chudieagle/.ssh/id_chudieagle_rsa
