---
- name: Ensuring EPEL repo
  dnf:
    name: epel-release.noarch
    state: present

- name: Installing Zabbix Repository
  dnf:
    name: '{{ centos_zabbixrepo }}'
    state: present
    disable_gpg_check: yes

- name: Installing Zabbix-Agent for CentOS
  dnf:
    name: zabbix-agent
    state: present

- name: Enable and start Zabbix-agent
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: Update the Zabbix Config files
  template:
    src: zabbix-agent.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent 

- name: Enusre firewalld is running
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Enabling ports for Zabbix-agent Serivces 
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ centos_zabbixagent_ports }}"

- name: "Adding {{ ansible_hostname }} to Zabbix"
  local_action:
    module: community.zabbix.zabbix_host
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_admin }}"
    login_password: "{{ zabbix_password }}"
    host_name: "{{ ansible_hostname }}"
    visible_name: "{{ ansible_hostname }}"
    description: "{{ ansible_hostname }}"
    host_groups:
      - Linux servers
      - Templates/Operating systems
    link_templates:
      - Linux by Zabbix agent
      - Zabbix Server
    interfaces:
      - type: '1'
        main: 1
        useip: 1
        ip: "{{ inventory_hostname }}"
        dns: ""
        port: "10050"
    status: enabled
    state: present
