---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Download the Zabbix Repo for Ubuntu 
  get_url:
    url: "{{ zabbix_ubuntu_url }}"
    dest: "{{ zabbix_ubuntu_dest_pkg }}"

- name: Install Zabbix Repo Ubuntu
  apt:
    deb: "{{ zabbix_ubuntu_dest_pkg }}/{{ zabbix_ubuntu_pkg }}"

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install Zabbix-agent for Ubuntu
  apt:
    name: zabbix-agent
    state: present

- name: Enable and Start services for zabbix-agent on ubuntu
  service:
    name: zabbix-agent
    state: started
    enabled: yes

- name: Enusre ufw Zabbix ports are open
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ubuntu_zabbix_ports }}"

- name: Update the Zabbix Config files
  template:
    src: zabbix-agent-ubuntu.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart ubuntu zabbix-agent

- name: "Adding {{ ansible_hostname }} to Zabbix"
  local_action:
    module: community.zabbix.zabbix_host
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_admin }}"
    login_password: "{{ zabbix_password }}"
    host_name: "{{ ansible_hostname }}"
    visible_name: "{{ ansible_hostname }}"
    description: "{{ ansible_hostname }}"
    host_groups:
      - Linux servers
    link_templates:
      - Linux by Zabbix agent
      - Zabbix Server
    interfaces:
      - type: '1'
        main: 1
        useip: 1
        ip: "{{ inventory_hostname }}"
        dns: ""
        port: "10050"
    status: enabled
    state: present
