- name: Create redis instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../gce_vars/auth
    - ../gce_vars/machines
    - ../gce_vars/zone
  tasks:
    - name: create a disk mapped for redisdev01 Centos8
      gcp_compute_disk:
        name: redisdev01-disk-instance
        size_gb: 100
        type: pd-ssd
        source_image: "{{ image }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk

    - name: create a redisdev VPC network
      gcp_compute_network:
        name: default
        auto_create_subnetworks: 'true'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: network

    - name: create a firewall rules for VPC
      gcp_compute_firewall:
        name: default
        network: "{{ network }}"
        allowed:
          - ip_protocol: icmp
          - ip_protocol: tcp
            ports:
              - '22'
              - '80'
              - '443'
              - '3389'
              - '10050-10051'
        source_tags:
          - http-server
          - https-server
          - shoplauncherdev
          - management
          - redis
          - elasticsearch
        source_ranges:
          - '0.0.0.0/0'
          - '130.211.0.0/22'
          - '35.191.0.0/16'
          - '209.85.152.0/22'
          - '209.85.204.0/22'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: firewall

    - name: create an IPv4 public IP Address
      gcp_compute_address:
        name: instance-1-stockcheck-redis
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: address

    - name: create the redisdev01 instance
      gcp_compute_instance:
        name: instance-1-stockcheck-redis
        machine_type: "{{ machine_type.redis }}"
        deletion_protection: yes
        disks:
          - index: 0
            auto_delete: 'no'
            boot: 'true'
            source: "{{ disk }}"
        labels:
          environment: redis-instance-sc
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - redis
        metadata:
          ssh_user: "{{ ssh_user }}"
          ssh_key: "{{ ssh_key }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: instance

    - name: Show redisdev01 Instance Details
      debug:
        msg: "The redisdev01 instance is accessible at {{ address.address }}"

    - name: Add redisdev01 to group redisdev01
      add_host:
        name: "{{ address.address }}"
        groups: redisdev

  post_tasks:
    - name: Wait for SSH for instance redisdev01 in first zone
      wait_for:
        delay: 30
        host: "{{ address.address }}"
        port: 22
        state: started
        timeout: 120

- hosts: redisdev
  roles:
    - users
    - redis
  gather_facts: True
  become: true
  vars:
    ansible_user: chudieagle
    ansible_ssh_private_key_file: /home/chudieagle/.ssh/id_chudieagle_rsa
