---
- name: Create obsolutely instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../gce_vars/auth
    - ../gce_vars/machines
    - ../gce_vars/zone
  tasks:
    - name: create a disk mapped for obsolutely - Ubuntu 20.04
      gcp_compute_disk:
        name: obsolutely-disk-instance
        size_gb: 500
        type: pd-ssd
        source_image: "{{ ubuntuimage }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk

    - name: create a VPC stockcheck network
      gcp_compute_network:
        name: stockchecker-subnetwork
        auto_create_subnetworks: 'true'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: network


    - name: create a firewall rules for VPC
      gcp_compute_firewall:
        name: obsolutely-fw-ports
        network: "{{ network }}"
        allowed:
          - ip_protocol: icmp
          - ip_protocol: tcp
            ports:
              - '22'
              - '80'
              - '443'
              - '10050'
              - '10051'
        target_tags:
          - obsolutely
        source_tags:
          - obsolutely
          - shoplauncherdev
          - management
          - greeneagle
          - redis
          - bitnami
          - elasticsearch
        source_ranges:
          - '0.0.0.0/0'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: firewall

    - name: create an IPv4 public IP Address
      gcp_compute_address:
        name: obsolutely-ins-ip
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: address

    - name: create the obsolutely instance
      gcp_compute_instance:
        name: obsolutely
        machine_type: "{{ machine_type.obsolutely }}"
        deletion_protection: yes
        disks:
          - index: 0
            auto_delete: 'no'
            boot: 'true'
            source: "{{ disk }}"
        labels:
          environment: obsolutely
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - obsolutely
        metadata:
          ssh_user: "{{ ssh_user }}"
          ssh_key: "{{ ssh_key }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: instance

    - name: Show obsolutely Instance Details
      debug:
        msg: "The obsolutely instance is accessible at {{ address.address }}"

    - name: Add obsolutely to group obsolutely
      add_host:
        name: "{{ address.address }}"
        groups: obsolutely

  post_tasks:
    - name: Wait for SSH for instance obsolutely in first zone
      wait_for:
        delay: 30
        host: "{{ address.address }}"
        port: 22
        state: started
        timeout: 120

- hosts: obsolutely
  roles:
    - users
    - zabbix-agent
    - apache
    - php74
    - mariadb
    
  gather_facts: True
  become: true
  vars:
    ansible_user: chudieagle
    ansible_ssh_private_key_file: /home/chudieagle/.ssh/id_chudieagle_rsa

  tasks:
    - name: "user wants git installed"
      apt:
        name: 
         - git
         - bash-completion
         - vim 
         - lsof
         - rsync
        state: present
