---
- name: Getting elastics01 info instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  tasks:
    - name: get info on elastics01 instance
      gcp_compute_instance_info:
        filters:
        - name = elastics01
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
      register: elastics01

    - name: Adding elastics01 instance to group elastics
      add_host:
        name: "{{ elastics01.resources[0].networkInterfaces[0].networkIP }}"
        groups: elastics

- hosts: elastics
  gather_facts: true
  become: true
  roles:
    - elasticsinstall
  vars:
    ansible_user: chudieagle
    ansible_ssh_private_key_file: /home/chudieagle/.ssh/id_chudieagle_rsa
