---
- name: Ensuring EPEL repo
  dnf:
    name: epel-release.noarch
    state: present

- name: Setup MariaDB Repo keys
  rpm_key:
    key: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    state: present

- name: Installing MariaDB repository
  yum_repository:
    name: MariaDB-10.5
    description: MariaDB repository for 10.5 packages
    baseurl: http://yum.mariadb.org/10.5/centos8-amd64
    gpgcheck: true
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

- name: Install MariaDB packages
  dnf:
    name:
      - mariadb-server
      - mariadb
      - python3-PyMySQL
    state: present

- name: Start the MariaDB Services
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: localhost
    password: "{{ centos_root_db_password }}"

- name: copy .my.cnf file with root password credentials
  template:
    src: templates/root/centos/.my.cnf
    dest: /root/.my.cnf
    owner: root
    mode: '0600'
  tags: cnf

- name: update mysql root password login for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ centos_root_db_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
  tags: rootpassword

- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: remove the test database
  mysql_db:
    name: test
    state: absent
    #Sample Database and User configurations
    #- name: add zabbix
    #  mysql_db:
    #    name: zabbix
    #    collation: utf8_bin
    #    encoding: utf8
    #    state: present
    #  notify: import zabbix schema
    #
    #- name: Meta Zabbix db
    #  meta: flush_handlers
    # 
    #
    #- name: add zabbix db user
    #  mysql_user:
    #    name: zabbix
    #    password: "{{ dbpass }}"
    #    priv: 'zabbix.*:ALL'
    #    host: localhost
    #    state: present
    #
    #
- name: Enusre firewalld is running
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Enabling ports for Mariadb Serivces 
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ centos_mariadb_ports }}"
