- name: Create kibana instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  tasks:
    - name: create a disk mapped for kibana - centos8
      gcp_compute_disk:
        name: kibana-disk-instance
        size_gb: 200
        type: pd-ssd
        source_image: "{{ image }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk

    - name: create a VPC stockcheck network
      gcp_compute_network:
        name: stockchecker-subnetwork
        auto_create_subnetworks: 'true'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: network

    - name: create a firewall rules for VPC
      gcp_compute_firewall:
        name: kibana-fw-ports
        network: "{{ network }}"
        allowed:
          - ip_protocol: icmp
          - ip_protocol: tcp
            ports:
              - '22'
              - '80'
              - '443'
              - '9200-9400'
              - '5600'
              - '5601'
              - '10050-10051'

        target_tags:
          - kibana
        source_tags:
          - kibana
          - stockcheck
          - shoplauncher   
          - management
          - greeneagle
          - redis
          - elasticsearch
        source_ranges:
          - '0.0.0.0/0'
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: firewall

    - name: create an IPv4 public IP Address
      gcp_compute_address:
        name: kibana-instance
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: address

    - name: create the kibana instance
      gcp_compute_instance:
        name: kibana
        machine_type: "{{ machine_type.kibana }}"
        deletion_protection: yes
        disks:
          - index: 0
            auto_delete: 'no'
            boot: 'true'
            source: "{{ disk }}"
        labels:
          environment: kibana
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - kibana
        metadata:
          ssh_user: "{{ ssh_user }}"
          ssh_key: "{{ ssh_key }}"
        zone: "{{ zone.za }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: instance

    - name: Show kibana Instance Details
      debug:
        msg: "The kibana instance is accessible at {{ address.address }}"

    - name: Add kibana to group kibana
      add_host:
        name: "{{ address.address }}"
        groups: kibana

  post_tasks:
    - name: Wait for SSH for instance kibana in first zone
      wait_for:
        delay: 30
        host: "{{ address.address }}"
        port: 22
        state: started
        timeout: 120

- hosts: kibana
  gather_facts: true
  become: true
  roles:
    - zabbix-agent
    - nginx
    - elasticsinstall
  vars:
    ansible_user: chudieagle
    ansible_ssh_private_key_file: /home/chudieagle/.ssh/id_chudieagle_rsa
