---
# handlers file for zabbix-agent
- name: restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted
 
- name: restart ubuntu zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
