---
# tasks file for users
- name: install tools centos
  dnf:
    name: "{{ tools }}"
    state: present
  when: ansible_distribution == "CentOS"

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install tools ubuntu
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ ubuntu }}"
  when: ansible_distribution == "Ubuntu"

- name: Ensure these groups are present.
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items:
    - "{{ groups_var }}"

- name: Ensure the list of users are present
  user:
    name: "{{ item.name }}"
    groups: "{{ item.group }}"
    state: present
    append: yes
  with_items:
    - "{{ users_var }}"

- name: copying users public keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  with_items:
    - "{{ ssh_pub_keys }}"

- name: coping private keys
  copy:
    src: "{{ item.privkey }}"
    dest: "/home/{{ item.name }}/.ssh/id_rsa"
    mode: 0600
  with_items:
    - "{{ ssh_private_keys }}"

- name: adding sudoers for webadmin
  template:
    src: templates/webadmin_sudoers.j2
    dest: /etc/sudoers.d/webadmin_sudoers

- name: adding sudoers for webadmin
  template:
    src: templates/sysadmin_sudoers.j2
    dest: /etc/sudoers.d/sysadmin_sudoers

- name: adding sudoers for webadmin
  template:
    src: templates/webadmin_sudoers.j2
    dest: /etc/sudoers.d/webadmin_sudoers

- name: adding sudoers for webadmin
  template:
    src: templates/sysadmin_sudoers.j2
    dest: /etc/sudoers.d/sysadmin_sudoers
