---
# tasks file for users
- name: install tools centos
  dnf:
    name: "{{ tools }}"
    state: present
  when: ansible_distribution == "CentOS"

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install tools ubuntu
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ ubuntu }}"
  when: ansible_distribution == "Ubuntu"

- name: Ensure these groups are present.
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items:
    - "{{ groups_var }}"

- name: Ensure the list of users are present
  user:
    name: "{{ item.name }}"
    groups: "{{ item.group }}"
    state: present
    append: yes
  with_items:
    - "{{ users_var }}"

- name: copying keys for manyondoma
  authorized_key:
    user: mndoma
    key: "{{ lookup('file', '/data/keys/id_mndoma.pub') }}"

- name: copying keys for chukwudi
  authorized_key:
    user: chukwudi
    key: "{{ lookup('file', '/data/keys/id_chukwudi.pub') }}"
    state: present

- name: copying keys for liberty
  authorized_key:
    user: liberty
    key: "{{ lookup('file', '/data/keys/id_liberty.pub') }}"
    state: present

- name: copying keys for liberty second key
  authorized_key:
    user: liberty
    key: "{{ lookup('file', '/data/keys/id_liberty2.pub') }}"
    state: present

- name: copying keys for liberty third key
  authorized_key:
    user: liberty
    key: "{{ lookup('file', '/data/keys/id_liberty3.pub') }}"
    state: present

- name: copying keys for tony
  authorized_key:
    user: tony
    key: "{{ lookup('file', '/data/keys/id_tony.pub') }}"
    state: present

- name: copying keys for kingsley
  authorized_key:
    user: kingsley
    key: "{{ lookup('file', '/data/keys/id_kingsley.pub') }}"
    state: present

- name: adding sudoers for webadmin
  template:
    src: templates/webadmin_sudoers.j2
    dest: /etc/sudoers.d/webadmin_sudoers

- name: adding sudoers for webadmin
  template:
    src: templates/sysadmin_sudoers.j2
    dest: /etc/sudoers.d/sysadmin_sudoers

- name: copying keys for tony
  authorized_key:
    user: tony
    key: "{{ lookup('file', '/data/keys/id_tony.pub') }}"
    state: present

- name: adding sudoers for webadmin
  template:
    src: templates/webadmin_sudoers.j2
    dest: /etc/sudoers.d/webadmin_sudoers

- name: adding sudoers for webadmin
  template:
    src: templates/sysadmin_sudoers.j2
    dest: /etc/sudoers.d/sysadmin_sudoers
