---
# handlers file for haproxy
- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    
- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
